### DISCUSSION TITLE
Double dash in CSS

### DISCUSSION THREAD

**Discussion by SamBenson** [cssbattle/forum#154] [Q&A]
Can someone explain all of the CSS in this submission? https://cssbattle.dev/play/71

I can't get my head around things like `dd{--:at 61%0,#0000,10q,#998235 0 21q,#1A4341 0;--a:95q/63q}`

What's with the `--` and the values being set? 🤔

**Comment by siva-kannan3** [comment]
@SamBenson it is just a css variable. Here -- is a variable name which holds some background gradient values.So we can later reuse it with var(name,fallback) function. Anyone correct me If I am wrong.

**Reply by gunnarbittersmann** [reply]
Correction: **custom property**. 😏

*“The biggest trick the devil every pulled was convincing people to call CSS custom properties ‘variables’.”*  
— [Kitty Giraudel](https://twitter.com/KittyGiraudel/status/966793340871200770)

**Comment by Beowolve** [comment]
`--` is the shortest variable you can create in CSS. Usually you would write `--<your var name>` but CSS also accepts just `--` as a variable.
You write `var(--,<default value>)` in your code and can then replace that part of CSS later by changing the variable for an other tag.

Lets say you want to paint circles with radial-gradient and different colors:
![image](https://user-images.githubusercontent.com/32326640/140025186-e9f02edb-c346-42cb-8d39-afda82671bd8.png)

Your first version might look like this:
```css
<style>
  *{background:
    radial-gradient(100px at 225px 150px,#F3AC3C 60%,#0000 0),
    radial-gradient(100px at 150px 150px,#6592CF 50%,#0000 0)#1A4341;
    margin:0;
  }
```

We are using radial-gradient twice and this gives us the chance to reuse code:
```css
<style>
  *{background:
    radial-gradient(100px at var(--,150px 150px,#6592CF 50%),#0000 0)var(--b,#1A4341);
    margin:0;
  }
  *+*{
    --:225px 150px,#F3AC3C 60%;
    --b: ;
  }
```

So what is happening here:
The `*` selector affects all html tags, and every html tag will get radial-gradient. But the vars `--` and `--b` are not set for `*`, so the default value are used.
`*+*` is a shorter version to select `body `, and there the vars `--` and `--b` are set. `--b` ist just used to basically delete the default color for the body tag and `--` changes position,color and size of the circle. By setting margin to 0, both the html tag and the body tag will overlap exactly and both circles will be drawn with different values.

Of course there are other optimizations for this code, but `var` alone saves us some chars in this example (if minimized). This is a very important feature, and many top solutions have one or more `var` usage in it.

**Reply by rafehimself** [reply]
and `* *` or `*>*`  would be what? html? they behave differently

**Reply by SelenIT** [reply]
`* *` and `*>*` mean "anything that is anything's descendant" and "anything that is anything's child" respectively, so they select _anything except `html`_ (because `html` doesn't have a parent element), i.e. `head`, `body` and _all their descendants_ (we don't see `head` because it has `display:none` by default, but it exists). `*+*` means "anything that is anything's next sibling", so in the empty HTML document it selects only `body` as the next sibling of `head`, and if `body` contains other elements, this selector doesn't select the first of them.

Also, it's worth noting that, per the latest spec, this shortest variable name `--` is reserved for use for resetting all custom properties at once (like the `all` shorthand for non-custom properties) and doesn't work in Firefox anymore, so solutions using it might stop working after one of the future Chromium updates.

**Reply by rafehimself** [reply]
hmmm but `*+*` doesn't work exactly like body in #91 
![image](https://user-images.githubusercontent.com/58576132/140335786-74f0dba1-fe16-45bc-83f7-6c68f0c705e3.png)

**Reply by SelenIT** [reply]
Yes, it selects `body` *and* all `p`s except the first one (it's the only element besides `html` and invisible `head` that doesn't have previous sibling). It will select only `body` only if it is empty or has just one child element.

**Reply by verberg** [reply]
> `--` is the shortest variable you can create in CSS. Usually you would write `--<your var name>` but CSS also accepts just `--` as a variable. You write `var(--,<default value>)` in your code and can then replace that part of CSS later by changing the variable for an other tag.
> 
> Lets say you want to paint circles with radial-gradient and different colors: ![image](https://user-images.githubusercontent.com/32326640/140025186-e9f02edb-c346-42cb-8d39-afda82671bd8.png)
> 
> Your first version might look like this:
> 
> ```
> <style>
>   *{background:
>     radial-gradient(100px at 225px 150px,#F3AC3C 60%,#0000 0),
>     radial-gradient(100px at 150px 150px,#6592CF 50%,#0000 0)#1A4341;
>     margin:0;
>   }
> ```
> 
> We are using radial-gradient twice and this gives us the chance to reuse code:
> 
> ```
> <style>
>   *{background:
>     radial-gradient(100px at var(--,150px 150px,#6592CF 50%),#0000 0)var(--b,#1A4341);
>     margin:0;
>   }
>   *+*{
>     --:225px 150px,#F3AC3C 60%;
>     --b: ;
>   }
> ```
> 
> So what is happening here: The `*` selector affects all html tags, and every html tag will get radial-gradient. But the vars `--` and `--b` are not set for `*`, so the default value are used. `*+*` is a shorter version to select `body `, and there the vars `--` and `--b` are set. `--b` ist just used to basically delete the default color for the body tag and `--` changes position,color and size of the circle. By setting margin to 0, both the html tag and the body tag will overlap exactly and both circles will be drawn with different values.
> 
> Of course there are other optimizations for this code, but `var` alone saves us some chars in this example (if minimized). This is a very important feature, and many top solutions have one or more `var` usage in it.

**Reply by verberg** [reply]
@SelenIT Thank you for this great explanation of variables. You use two layers `*` and` *>*`, but have you any idea, what to do, when I need 3 layers? I tried it in target #79, where I solved the background width 3 radial-gradients, but I need somehow a third layer.
Here my solution for the background:
`<style>*{background:radial-gradient(1q,#0000,90q,#6592CF)50%10q,radial-gradient(1q,#6592CF 53q,0,#243D83 64q,0,#0000)50%418q,radial-gradient(1q,#6592CF 79q,0,#243D83 90q,0,#0000)50%10q}`
Thanks for your reply! - the foreground I solved already with variables!

**Reply by Beowolve** [reply]
You can add an extra layer by adding a `<p>` element for example and give it enough height to cover the area you need. 

So if we extend the example from above to this:
```css
<style>
*{background:
  radial-gradient(100px at 225px 150px,#F3AC3C 60%,#0000 0),
  radial-gradient(100px at 185px 100px,#FFEECF 40%,#0000 0),
  radial-gradient(100px at 150px 150px,#6592CF 50%,#0000 0)#1A4341;
  margin:0;
}
```
Would then transform into this:
```css
<p>
<style>
*{background:
  radial-gradient(100px at var(--,150px 150px,#6592CF 50%),#0000 0)var(--b,#1A4341);
  margin:0;
}
*+*{
  --:185px 100px,#FFEECF 40%;  
  --b: ;
}
p{
  height:284;
  --:225px 150px,#F3AC3C 60%;
}
```
