### DISCUSSION TITLE
Target#91 - Reflection

### DISCUSSION THREAD

**Discussion by Beowolve** [cssbattle/forum#161] [General]
While doing [Target#91](https://cssbattle.dev/play/91) I stored a lot of in between steps leading to the current top solution. At the time when I started, @SelenIT solution was top, therefore I have no versions before that time.

Does anyone have another interesting or creative solution?

Nice `em `trick from @SelenIT, by the way! 👍 
Also, that `space` keyword for linear-gradient you used in your earlier solution was new to me. I haven't even found a description for that somewhere online!?

Here is everything I have collected in reverse order:

## 125 @SelenIT (ilya)
```css
<p>.<p>.<p>.<p>.<style>*{margin:75 0-65;background:radial-gradient(1q,#F6DF96 106q,#D25B70 0 775em,#6CB3A9)fixed;font:9%/5vh'
```

## 128 Weltyn
```css
<p>.<p>.<p>.<p>.<style>*{margin:75 0-65;background:radial-gradient(1q,#F6DF96 36.3ex,#D25B70 0 6950em,#6CB3A9)fixed;font:3%/5vh
```

## 134 Gabriel David
```css
<p>.<p>.<p>.<p>.<style>*{background:radial-gradient(1em,#F6DF96,625%,var(--,#D25B70))fixed;margin:75 0-65}* *{--:#6CB3A9}p{font:0/16q'
```

## 136 @iamvdo
```css
<p>.<p>.<p>.<p>.<style>*{background:radial-gradient(1em,#F6DF96,625%,var(--,#D25B70))fixed}* *{margin:150 0-140;--:#6CB3A9}p{font:0/16q'
```

## 146 @PolariTOON (tristan)
```css
<p>.<p>.<p>.<p>.<style>*>*{font:0/5vh a;margin:150 0-140;background:radial-gradient(6em,#F6DF96,104%,#0000),linear-gradient(#D25B70 20ch,#6CB3A9 0
```

## 147 @PolariTOON (tristan)
```css
.<p>.<p>.<p>.<p>.<style>p{font:0/5vh a}*>*{margin:66 0-56;background:radial-gradient(6em,#F6DF96,104%,#0000),linear-gradient(#D25B70 20ch,#6CB3A9 0
```

## 149 @SelenIT (ilya)
```css
<p>.<p>.<p>.<p>.<style>p{margin:150 0-140;font:0/5vh a}*>*{background:radial-gradient(6em,#F6DF96,104%,#0000),linear-gradient(#D25B70 9.4em,#6CB3A9 0
```

## 150 @SelenIT (ilya)
```css
<p>.<p>.<p>.<p>.<style>p{margin:150 0-140;font:0/5vh a}*>*{background:radial-gradient(1q,#F6DF96,6.25em,#0000),linear-gradient(#D25B70 9.4em,#6CB3A9 0
```

## 151 @SelenIT (ilya)
```css
<p><p><p><p><style>*{border-bottom:solid#6CB3A9 50vh}body{background:#D25B70;border-top:dotted#F6DF96 50vw;margin:50 100-400}p{zoom:.1;margin:-50%0 55%
```

## 152 @SelenIT (ilya)
```css
<p><p><p><p><style>p{height:15;margin:150 0-140;font:0 a}*>*{background:radial-gradient(1q,#F6DF96,6.25em,#0000),linear-gradient(#D25B70 9.4em,#6CB3A9 0
```

```css
<style>* *{--:top/1%25px}*{padding:33%0 0;background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),top/1%125%#D25B70)linear-gradient(#0000 40%,#6CB3A9 0
```

## 157 @PolariTOON (tristan)
```css
<p><p><p><p><style>p{height:15;margin:150 0-140;--:#6CB3A9}*>*{background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```
```css
<p><p><p><p><style>p{height:30;margin:135 0-140;--: }*>*{background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),#D25B70)linear-gradient(#0000 50%,#6CB3A9 0
```

## 158 @Beowolve 
```css
<p><p><p><p><style>p{height:15;margin:10;box-shadow:0 35vw#6CB3A9}html{background:radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

## 159 @Beowolve 
```css
<p><p><p><p><style>p{height:15;margin:10;box-shadow:0 140px#6CB3A9}html{background:radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

## 159 @iamvdo
```css
<style>*+*{height:15;color:6CB3A9;box-shadow:0 150Q,0 177Q,0 2IN,0 230Q;background:radial-gradient(1q,#F6DF96,106q,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

## 160 @iamvdo
```css
<style>*+*{background:radial-gradient(1q,#F6DF96,106q,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0);height:15;color:6CB3A9;box-shadow:0 150Q,0 177Q,0 2IN,0 230Q
```

## 161 @Beowolve 
```css
<p><p><p><p><style>p{height:15;margin:10 0;box-shadow:0 140px#6CB3A9}html{background:radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

## 162 @Beowolve 
```css
<p><p><p><p><style>p{height:15;margin:10-10;box-shadow:0 140px#6CB3A9}body{background:radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

## 178 @SelenIT (ilya)
```css
<style>*{background:radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0)}*+*{background:repeating-linear-gradient(#6CB3A9 0 5vh,#0000 0 25px)space 0 150q
```

**Comment by rafehimself** [comment]
nice but that was imvdo
i had lead around 198

`<style>*{background:linear-gradient(#D25B70 50%,#6CB3A9 0)}*+*{border-radius:50%;margin:50 100;background:linear-gradient(#F6DF96 50%,#0000 0),repeating-linear-gradient(#6CB3A9,5vh,#F6DF96 5vh 25px`

tried to make custom properties but I didn't succeed with that and then Iyla came 🤣 

slightly shorter version of it 193
```<style>*{background:linear-gradient(#D25B70 50%,#6CB3A9 0)}*+*{background:linear-gradient(#F6DF96 50%,#0000 0),repeating-linear-gradient(#6CB3A9,5vh,#F6DF96 5vh 25px)0 18q;clip-path:circle(25vw```

**Reply by Beowolve** [reply]
Thx for the correction

**Comment by RazvanManolache** [comment]
thank you! I have been trying to catch the same thing and refreshing and refreshing because there's a ton to learn from  the process, more so than from the best solution.

the current solution is killer because if I interpret it correctly, I don't understand it. :)

`<p>.<p>.<p>.<p>.<style>*>*{font:0/5vh a;margin:150 0-140;background:radial-gradient(6em,#F6DF96,104%,#0000),linear-gradient(#D25B70 20ch,#6CB3A9 0
`

if anybody can clarify, I would be grateful. Basically it's using units that have different values depending on the container?

**Reply by rafehimself** [reply]
yeah can someone explain why em works differently than other units? and what is ch

**Reply by RazvanManolache** [reply]
don't know either, just reading that https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

probably it help if you try to make the big version with style for each p, and then change to pixels to find out what the hell is going on.

**Reply by rafehimself** [reply]
i mean if u put other units than em, the out put is totally different
![image](https://user-images.githubusercontent.com/58576132/140415940-d51c5dce-1481-446b-a7ca-c188c5c37922.png)
p will be outside of circle

**Reply by SelenIT** [reply]
The current solution uses a bit weird (though [specified](https://drafts.csswg.org/css-backgrounds/#body-background)) behavior of the `background` property: if there is no background set for the `html` element, the background of the `body` element is "propagated" to it and applied to `html` instead of `body`. So this background declaration is "propagated" to `html` and uses the default font size (16px per `1em`) in all calculations, since the `font-size` of `html` was unchanged. Then, in all descendants of `html` (i.e. `body` and all 4 `p`s), font size becomes zero, so the radius of the yellow circle and the height of the red stripe become zero too, leaving only the green stripe in the background. It doesn't have any effect on `body`, since its background has been "propagated" to `html` (so `body` actually has transparent background), but makes the background of `p`s green. Finally, the height of nonempty `p`s is their `line-height` set in the same `font` shorthand, and the top margins of `body` and the first `p` "collapse", so the distance between the top edge of `html` and the top edge of the first `p` is 150px (not 300px), exactly as needed.

The `ch` unit is the width of the `0` character in the font being used, so it also becomes 0 if the font-size is 0. However, for very small but nonzero font-size values, both `ch` and `ex` units might behave differently from `em`, because they are derived from the *used* font size, not the *specified* `font-size`, and obey the minimum font-size setting of the browser. We don't see that difference in this solution, but sometimes it can be useful (e.g., it helped me in [#78](https://cssbattle.dev/play/78) 😀).

**Reply by RazvanManolache** [reply]
:)))) for #78 you used the difference between ch and ex? We're fuckin' doomed.

**Reply by SelenIT** [reply]
This solution for [#91](https://cssbattle.dev/play/91) shows that difference between `ex` and `em` (though it turned out not necessary for this particular target):
```
<p>.<p>.<p>.<p>.<style>*{margin:75 0-65;background:radial-gradient(1q,#F6DF96 36.3ex,#D25B70 0 6950em,#6CB3A9)fixed;font:3%/5vh'
```
Here, the deeper the element is nested, the smaller becomes its specified font size (`html` has font-size of 3% of default, `body` has font-size of 3% of `html`, and so on), so inner radius of the green zone gets smaller and smaller. But the rendered font is clamped at some minimum value (often something around `6px`), so units derived from it (`ex` and `ch`) stop getting smaller at some point, and the yellow zone radius becomes constant despite decreasing `font-size` until it gets rounded to zero.

**Reply by rafehimself** [reply]
how is that 100% ... 👀

**Reply by SelenIT** [reply]
It's 100% on backend, with its default font and its minimum limit 😳

**Reply by rafehimself** [reply]
why there is a difference? depends on device or how it works

**Reply by SelenIT** [reply]
Different devices (especially with different OSes) often have different default fonts, and `ex`/`ch` units are calculated from the metrics of these fonts, which are font-specific

**Reply by rafehimself** [reply]
![image](https://user-images.githubusercontent.com/58576132/140824075-7599fe76-25a8-4910-bd5a-5d21a59a91a8.png)
on my screen 😃 , win11 + chrome

**Comment by gunnarbittersmann** [comment]
I was late to the party. So thanks for keeping track. Included to https://bittersmann.de/cssbattle/open-targets/

**Reply by gunnarbittersmann** [reply]
Diff comments added. https://bittersmann.de/cssbattle/open-targets/91.txt

**Comment by PolariTOON** [comment]
This also lacks this 157 chars solution of mine based on Beo's solution in 158.
This was at the top for about half an hour before Ilya took the lead again:

```html
<p><p><p><p><style>p{height:15;margin:150 0-140;--:#6CB3A9}*>*{background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),linear-gradient(#D25B70 50%,#6CB3A9 0
```

**Reply by PolariTOON** [reply]
In the meantime, while trying to shorten the previous solution even further, I also found this other solution, but this was also in 157:

```html
<p><p><p><p><style>p{height:30;margin:135 0-140;--: }*>*{background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),#D25B70)linear-gradient(#0000 50%,#6CB3A9 0
```

**Reply by Beowolve** [reply]
Updated

**Comment by SelenIT** [comment]
One more 152-char solution with no extra markup, just for collection:
```CSS
<style>* *{--:top/1%25px}*{padding:33%0 0;background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),top/1%125%#D25B70)linear-gradient(#0000 40%,#6CB3A9 0
```

**Reply by Beowolve** [reply]
> One more 152-char solution with no extra markup, just for collection:
> 
> ```css
> <style>* *{--:top/1%25px}*{padding:33%0 0;background:var(--,radial-gradient(1q,#F6DF96,25vw,#0000),top/1%125%#D25B70)linear-gradient(#0000 40%,#6CB3A9 0
> ```

added

**Comment by SelenIT** [comment]
And one more, 151 char 😃
```CSS
<p><p><p><p><style>*{border-bottom:solid#6CB3A9 50vh}body{background:#D25B70;border-top:dotted#F6DF96 50vw;margin:50 100-400}p{zoom:.1;margin:-50%0 55%
```
