### DISCUSSION TITLE
#Target92

### DISCUSSION THREAD

**Discussion by GaganPrasad** [cssbattle/forum#162] [Q&A] [answered]
I get 100% when I use background #6592CF
`<style>*{background:#6592CF}*>*{margin:50 100;background:#243D83;color:243D83;box-shadow:239q 0,-239q 0,120q 28q 0-84px#6592CF,120q -28q 0-84px#6592CF,-120q 28q 0-88q#6592CF,-120q -28q 0-84px#6592CF,-120q 0 0-75q,120q 0 0-75q;border-radius:50%`

but get 99.9% when box shadow is used even tho i see no change visually 
`<style>*>*{margin:50 100;background:#243D83;color:243D83;box-shadow:239q 0,-239q 0,120q 28q 0-84px#6592CF,120q -28q 0-84px#6592CF,-120q 28q 0-88q#6592CF,-120q -28q 0-84px#6592CF,-120q 0 0-75q,120q 0 0-75q,0 0 0 9in#6592CF;border-radius:50%`

also any suggestion to reduce this.

**Comment by rafehimself** [comment, marked as answer]
there is a difference tiny 6592CF line
![image](https://user-images.githubusercontent.com/58576132/140420830-c6228fd5-c3f1-4ed7-9b1a-1f2ed806c02c.png)

**Comment by rafehimself** [comment]
I don't want to make another thread, cuz it's the same target, but different dilemma, so I post here

I wonder is there 1 cohesive syntax to achieve the same ? without repetition of the world background 3 times 😆 

`<style>*+*{background:radial-gradient(1q,#243d83,25vw,#6592cf);background-size:226px 300px;background-position:87`

![image](https://user-images.githubusercontent.com/58576132/140474034-4598629c-6d74-4566-8921-3b90f3a844bb.png)

I'm guessing Mr Cooper Forest used something different anyways

**Reply by Beowolve** [reply]
You can write the following for the same result.
`<style>*+*{background:radial-gradient(1q,#243d83,25vw,#6592cf)50%/226px`

Never use background-size or background-position, use that shorthand syntax for it.

**Comment by GaganPrasad** [comment]
`<style>*{background:#6592CF}*>*{margin:50 100;background:#243D83;color:243D83;box-shadow:239q 0,120q 28q 0-88q#6592CF,120q -28q 0-89q#6592CF,120q 0 0-75q;border-radius:50%;-webkit-box-reflect:left -50vw`

I tried to improve on my code but it gives 99.9% I don't understand - for this if I use box-shadow instead of box-reflect it's 100% 

using px - same code `<style>*{background:#6592CF}*>*{margin:50 100;background:#243D83;color:243D83;box-shadow:226px 0,113px 26px 0-84px#6592CF,113px -26px 0-84px#6592CF,115px 0 0-72px;border-radius:50%;-webkit-box-reflect:left -50vw`

**Reply by rafehimself** [reply]
looks the same to me, machine is stupid 🤣 
another bug with border-radius I guess,
@chinchang

**Reply by gunnarbittersmann** [reply]
What you call “bugs” I call “challenges”. 😉
It’s not that I haven’t run into one or two of these. Or five. Or ten.

**Reply by rafehimself** [reply]
ok there are ways to omit that, but I don't see a valid reason why for example that solution is rejected by machine , when it's nothing wrong with that approach other than a bug in calculating pixels

**Reply by Beowolve** [reply]
I have seen this problem happen a lot with `-webkit-box-reflect`, so I try to avoid it. Sometimes it helps if you switch from `left` to `right`. So place all elements to the other side and try that, maybe it works. For reaching a high score, I would advise you to try radial-gradient anyway. At least 122 is possible, that I know for sure :wink:.
How @gunnarbittersmann, @SelenIT and Mr. Copper Forest managed to do go below that is another story I suppose. You guys know a lot of tricks, for sure! Any tips of which direction to look for a better version, a smarter use of `radial-gradient` or did you guys switch to Unicode?

**Reply by gunnarbittersmann** [reply]
Good ol’ `radial-gradient`.
And yes, how @SelenIT got down to 113 is beyond my comprehension.

**Reply by Beowolve** [reply]
> Good ol’ `radial-gradient`. And yes, how @SelenIT got down to 113 is beyond my comprehension.

You are just 1 char behind his solution, that seems doable. Somehow I find new ways to optimize after I slept one night and the next time I look at it, there is an idea in my head.

**Reply by rafehimself** [reply]
you guys have just one gradient? 👀 
at least I managed to go below 200 (174 ) with 3 gradients 2x radial and linear thanks to your tip @Beowolve 
however I don't yet how make custom properties with that addition values at the end of gradient, outside of bracket (),
I will need to do some reading on that,
overall to be competitive in top10 reading CSS specification as a hobby seems to be a must 🤣

**Reply by gunnarbittersmann** [reply]
> You are just 1 char behind his solution, that seems doable.

Sometimes 1 character is a microöptimization; sometimes it’s a different approach.

**Reply by SelenIT** [reply]
My solution is still radial-gradient, but it exploits the scoring algorithm’s tolerance to *visible* differences in the resulting shape 😳 and it took hundreds of attempts to find the fitting combination.

For using custom properties for sub-properties of the `background` shorthand (and other shorthands, for that matter), the following approach often helps: first write the shorthand without them, noticing the repeating parts, then isolate the unique parts and move them to the custom property.

**Reply by arjun-g** [reply]
My solution involves 2 custom property, hopefully i can make it to one. But I am still unable to figure out how you folks remove the repeating color hex code in the gradient 🧐.

**Reply by SelenIT** [reply]
Ironically, my current shortest solution has the repeating color in it 😃

**Reply by rafehimself** [reply]
![image](https://user-images.githubusercontent.com/58576132/140651336-a311d88e-f28a-41da-9fb5-54b04c30a4fa.png)
I found that to be working as 100% 🤣  quite bizarre, tolerance for gradients seems to be more loose?

`<style>*{background:
radial-gradient(1q,#6592CF,5vh,#0000)-21%18%/239q 53q,
radial-gradient(1q,#243D83,5vh,#0000)-21%6%/1q 3in,
radial-gradient(1q,#243d83,25vw,#6592cf)50%/239q`

a lot of repetitions so it must have potential to be reduced, but I can't get my head fully around those custom property yet

`<style>*{background:radial-gradient(1q,var(--,#243d83,25vw,#6592cf))var(--a,50%/239q)}* *{--:#ffF,5vh,#0000;--a:-21%18%/239q 53q;`
that's where I get so far by breaking down the tigger code, is that the shorter I can get? not even close to the top,
![image](https://user-images.githubusercontent.com/58576132/140652410-27c0a47e-519e-4a65-949f-583e326eb6fb.png)

and I need one more gradient after coma which doesn't work 😞 CSS is tough

**Reply by arjun-g** [reply]
> Ironically, my current shortest solution has the repeating color in it 😃

So I have to play with the background position and size then 😁

**Reply by SelenIT** [reply]
@rafehimself the power of custom properties usually can be seen if there are several selectors with much common styling, but some different details. For example, if these three radial gradients were applied to 3 elements instead of one (208 chars in total when minified):
```CSS
<dt><style>
*{
  background:radial-gradient(1q,#243d83,25vw,#6592cf)50%/239q
}
*+*{
  background:radial-gradient(1q,#243D83,6vh,#0000)0/1%
}
dt{
  height:284; /* 300 - 2*8 - default body margins */
  background:radial-gradient(1q,#6592CF,5vh,#0000)-21%18%/239q 53q
```
...you can reuse the `background:radial-gradient(1q, ... )` part and change only the parenthesed part and the position/size outside, like this:
```CSS
<dt><style>
*{
  background:radial-gradient(1q,var(--r,#243d83,25vw,#6592cf)) var(--,50%/239q)
}
*+*{
  --r:#243D83,6vh,#0000;
  --:0/1%
}
dt{
  height:284;
  --r:#6592CF,5vh,#0000;
  --:-21%18%/239q 53q
```
...reducing the minified code to 178 chars.

Then, you can notice that two of three gradients start with `#243D83`, so you can add the zero-sized zone of that color to the third gradient (it will have no visible effect) and move that color to the constant part, shaving 5 more characters from the solution:

```CSS
<dt><style>
*{
  background:radial-gradient(1q,#243d83,var(--r,25vw,#6592cf))var(--,50%/239q)
}
*+*{
  --r:6vh,#0000;
  --:0/1%
}
dt{
  height:284;
  --r:#6592CF 0 5vh,#0000;
  --:-21%18%/239q 53q
```

Finally, since the `background` shorthand allows the combination of position/size be either before or after the image, and custom variables will be set only for `body` and `dt`, but not `html`, you can reorder the solution so that it will end with two parentheses, which can be omitted, shortening it 2 characters more:

```CSS
<dt><style>*+*{--r:6vh,#0000;--:0/1%}dt{height:284;--r:#6592CF 0 5vh,#0000;--:-21%18%/239q 53q}*{background:var(--,50%/239q)radial-gradient(1q,#243d83,var(--r,25vw,#6592cf
```

It was just to illustrate the idea. Of course, there are many other ways of optimisation. Good luck in golfing! 🍀
