### DISCUSSION TITLE
How many ways to draw a circle are there in CSS?

### DISCUSSION THREAD

**Discussion by SelenIT** [cssbattle/forum#177] [General]
Since the ongoing Battle is circle-themed, let's recall how a circle can be drawn in CSS (and HTML)!

* `border-radius`
  * ...and solid `background`
  * ...and `border`
  * ...and `box-shadow`
    * external (outside element boundaries)
    * `inset`
* `radial-gradient`
   * ...as `background`
   * ...as `border-image`
   * ...with `circle` keyword or single radius...
   * ...or without it, if the image aspect ratio is 1:1
* `border-*: <diameter> dotted`
*  `clip-path`
   * ... `circle(<radius>)`
   * ... `inset(<offsets to make a square> round <radius>)`
   * ... anything else? 😉
* unicode character (there are tons of!)
   * ... including default list marker of the `<li>` element
* `mask`

...what have I missed? 😃

And which do you use/like more?

**Comment by jacobovillegas** [comment]
Nice post! also ...dotted border?

**Comment by rafehimself** [comment]
example of a mask ? 😃 
in normal world `outline` should work as well and outline dotted

**Comment by Beowolve** [comment]
Here are some examples for drawing a circle with different methods. 

## circles with border
Lets say you wanna draw this:
![image](https://user-images.githubusercontent.com/32326640/142587547-74d368be-a0b0-401f-b6a0-d3b616ab2747.png)


### radial-gradient

```css
<style>*{background:radial-gradient(1q,#A64942,80px,#FE5F55 0 100px,#191919)}
```

### border-radius + border

```css
<style>*{background:#191919}*>*{background:#A64942;border-radius:50%;border:solid 20px#FE5F55;margin:50 100}
```

### border-radius + box-shadow
```css
<style>*{background:#191919}*>*{background:#A64942;border-radius:50%;box-shadow:0 0 0 20px#FE5F55;margin:70 120}
```

### border-radius + box-shadow (inset)
```css
<style>*{background:#191919}*>*{background:#A64942;border-radius:50%;box-shadow:inset 0 0 0 20px#FE5F55;margin:50 100}
```

### border-radius with outline (doesn't work in backend at the moment!)
```css
<style>*{background:#191919}*>*{background:#A64942;border-radius:50%;outline:solid 20px#FE5F55;margin:70 120}
```
![image](https://user-images.githubusercontent.com/32326640/142588142-472f7c7f-0964-4618-81ca-05fb1cefdcfb.png)

## simple circles

![image](https://user-images.githubusercontent.com/32326640/142592753-9e3caf51-54f2-4cc3-bfb3-9f665cb21a57.png)

### clip-path
With clip-path you can't create a border unless u use multiple clip-paths, but it has other advantages and its very useful for targets like the [Great Wall #93](https://cssbattle.dev/play/93).

A simple circle can be drawn like this
```css
<style>*{background:#191919}*>*{background:#FE5F55;clip-path:circle(25vw)}
```
or with Inset:
```css
<style>*{background:#191919}*>*{background:#FE5F55;clip-path:inset(50px 100px round 1in)}
```
Inset isn't useful here because of the longer code, but you can use it for other shapes like for target [Sunset #62](https://cssbattle.dev/play/62).


### border - dotted
```css
<style>*{background:#191919}*>*{margin:50 100;border-top:200px dotted#FE5F55}
```

### li-tag
The `<li>` tag has a circle by the default and u can position it with margins.
```css
<li><style>*{background:#191919}*>*{color:#FE5F55;font:650%/0 a;margin:122 50}
```

**Comment by RazvanManolache** [comment]
just wanted to say thank you for an initiative to explain something that I was embarrassed to ask.

**Comment by Beowolve** [comment]
## radial-gradient examples

In my opinion, radial-gradient is the most useful option of all these choices, so here is a list of some examples showing some shorthand options you have. If also shows what happens if you draw with "at" or use the offsets outside the radial-gradient definition. Note, you can use this shorthand notation before or after your gradient.

### centered transparent ring
![image](https://user-images.githubusercontent.com/32326640/142668698-e095c43d-e4f9-4645-bde7-bdbd00f9d823.png)

```css
<style>*{background:radial-gradient(1q,#0000,80px,#FE5F55 0 100px,#0000)#191919}
```
### ring touching the left border positioned with at
![image](https://user-images.githubusercontent.com/32326640/142668656-ba6e8846-53b2-4239-91b3-ca676a4f949e.png)

```css
<style>*>*{background:radial-gradient(1q at 100px,#0000,80px,#FE5F55 0 100px,#0000)#191919}
```

### ring touching the left border positioned with offset
![image](https://user-images.githubusercontent.com/32326640/142668650-59c3df59-c737-43a3-ac83-44dc0afaae64.png)

```css
<style>*>*{background:radial-gradient(1q,#0000,80px,#FE5F55 0 100px,#0000)-100px #191919}
```

### ring at top/left positioned with at
![image](https://user-images.githubusercontent.com/32326640/142668579-3aa30fc9-24c3-4ed5-97c0-dc571f9729b1.png)

```css
<style>*>*{background:radial-gradient(1q at 0%0,#0000,80px,#FE5F55 0 100px,#0000)#191919}
```

### ring at top/left position with at and different background size
![image](https://user-images.githubusercontent.com/32326640/143719799-a05a8eca-660c-4b1a-9e33-48b0225f0a91.png)
```css
<style>*>*{background:radial-gradient(1q at 0%0,#0000,80px,#FE5F55 0 100px,#0000)0 0/50%50%#191919}
```


### ring at top/left positioned with offset
![image](https://user-images.githubusercontent.com/32326640/142668514-89e642e4-88ab-4a9c-8aa2-73e6995e363e.png)

```css
<style>*>*{background:radial-gradient(1q,#0000,80px,#FE5F55 0 100px,#0000)-200px -150px #191919}
```

### two rings
![image](https://user-images.githubusercontent.com/32326640/142668447-62859b3d-8e41-4134-a2f8-e9b70638fef3.png)

```css
<style>*>*{background:radial-gradient(1q,#0000,80px,#FE5F55 0 100px,#0000)0/50% #191919}
```

### four rings
![image](https://user-images.githubusercontent.com/32326640/142668376-f5c46433-ecfa-4a3c-be7b-937898595071.png)

```css
<style>*>*{background:radial-gradient(1q,#0000,50px,#FE5F55 0 70px,#0000)0 0/50%50% #191919}
```

### 9 semi dimaond shapes with radial-gradient and parameters befor radial-gradient
![image](https://user-images.githubusercontent.com/32326640/142668258-85f4b5bd-7bb0-4631-9465-8df4a20db499.png)

```css
<style>*>*{background:30%17%/30%40%radial-gradient(1q,#0000,70px,#FE5F55 0 100px,#0000)#191919}
```

**Reply by SelenIT** [reply]
For quarter-rings at all four corners (reminds of [target #20](https://cssbattle.dev/play/20) 😀), you can use positive offset values as well. Since the pattern is repeated infinitely by default, the same result can be achieved by moving the "initial" fragment in any direction. Also, moving the pattern by the whole number of the "tile" dimensions results in the same image, so only the remainder from dividing the offset by the size of the "tile" matters. This can be used in golfing, e.g. for moving a 200px-wide pattern by `88px` you can instead move it by `3in` (which is 288px).

**Comment by SelenIT** [comment]
Since the last example is not a circle, I'd like to add another useful feature of radial gradients: you can take a thin (1px wide) stripe from the center of the gradient and repeat it, effectively turning a radial gradient into symmetric linear. For example, [target #63](https://cssbattle.dev/play/63) can be solved with just one gradient, like this:

```CSS
<p><a><style>
a{
  /* makes it overlay the parent, vertical margins for inlines are ignored */
  margin: -64;
  /* top layer, horisontal stripes with transparent background
     only y-position, only x-size */
  --props: 0%.5q / 1q
}
p{
  /* second top layer, vertical stripes with opaque dark background
     only x-position, both x- and y-sizes since you can't set the latter without the former */
  --props:2q/99%1%#191919
}
*+*{
  /* second bottom layer (body), four circles placed as needed by both size & position */
  --props: 7%-30% / 46.7%61.2%
}
*{
  /* makes sizes of all elements in the solution good enough to get 💯 */
  padding: 44 64;
  background:
    /* one background to rule them all 🧙‍♂️ */ 
    radial-gradient(1q,#0000 26q,#5DBCF9 0 35px,#0000)
    /* bottom layer (html), dark background, central circle will be overlaid with the p element  */
    var(--props, #191919)
}
```

The resulting image gets constructed like this:
<img width="400" alt="Screenshot 2021-11-19 at 23 31 19" src="https://user-images.githubusercontent.com/282754/142689283-261c7dbb-2b7f-4f93-9272-644744e1dd46.png">

This approach also worked quite well for me in [#74](https://cssbattle.dev/play/74) (got 356 chars with it) and might be useful in other cases as well (maybe even in real development? 😃)

Also, the last example above suggests that you actually can make a rectangle with a radial gradient. This fact might be helpful in targets like [#3](https://cssbattle.dev/play/3) and [#9](https://cssbattle.dev/play/9)... 😉

**Reply by RazvanManolache** [reply]
I have 111 chars or #3. You most likely did that method too. You're telling me that for 109 chars you had to redo your whole strategy and do crazy stuff like that?

**Reply by SelenIT** [reply]
Unfortunately, 109 seems not possible anymore with the current backend, it exploited the Chromium bug with the possibility to specify sub-properties of the `background` shorthand in the wrong order that has been fixed since that. But it's still possible to get 110 with `background` only, by correct choice of `background-size` and `background-repeat` parts.

**Reply by SelenIT** [reply]
Upd: it turns out that 108 chars are now available with just one `background` for #3!

**Comment by Beowolve** [comment]
## circle segments with background gradients

Here is a list of different methods for drawing a circle segment, with background gradients.

All examples show this image:
![image](https://user-images.githubusercontent.com/32326640/143446684-a86348c1-d6c3-4010-a7aa-b8d1df1b007d.png)

### conic-gradient + border-radius

```css
<style>*{background:#1A4341}
*>*{
  margin:50 100;
  border-radius:50%;
  background:
    conic-gradient(from 315deg,#F3AC3C,25%,#1A4341 0)
}
```

### conic-gradient + clip-path

```css
<style>*{background:#1A4341}
*>*{
  clip-path:circle(25vw);
  background:
    conic-gradient(from 315deg,#F3AC3C,25%,#1A4341 0)
}
```

### linear-gradient + border-radius

```css
<style>*{background:#1A4341}
*>*{
  margin:50 100;
  border-radius:50%;
  background:
    linear-gradient(45deg,#1A4341 50%,#0000 50%),
    linear-gradient(135deg,#F3AC3C 50%,#0000 50%);
}
```

### radial-gradient

```css
<style>*{background:#1A4341}
*>*{
  margin:50 100;
  transform:rotate(-45deg)translate(100px,-100px);
  background:
    radial-gradient(1q at 0%100%,#F3AC3C,106q,#1A4341 0)
}
```

**Reply by gunnarbittersmann** [reply]
Look Ma, no gradients!
### border + border-radius
```css
<style>*+*{
  background:#1A4341;
  margin:50 100;
  border-radius:9in;
  border:25vw solid;
  border-color:F3AC3C#0000#0000;
}
```
