### DISCUSSION TITLE
Target #55 It's possible to improve this?

### DISCUSSION THREAD

**Discussion by Gabb192** [cssbattle/forum#236] [Q&A] [answered]
Hey there,

Been trying to improve my high score on [target #55](https://cssbattle.dev/play/55) but i can't find the right pixel..

`<b><c><d><style>*{background:#191919;border-radius:53q 53q 0 0;position:fixed;margin:50}*>*{width:100;height:50;background:#F9E492;transform-origin:100px 0}b,d{background:#4F77FF}b,c,d{transform:rotate(90deg`

This is my record whit 207 charcters. I was wonder if it's possible to sobstitute width and height with padding like so

`<b><c><d><style>*{background:#191919;border-radius:53q 53q 0 0;position:fixed;margin:50}*>*{padding:25 50;background:#F9E492;transform-origin:93q -39.16q}b,d{background:#4F77FF}b,c,d{transform:rotate(90deg`

But whit this solution i only got 99,9% because of the transform-origin, any suggestions?

Thanks for give me an idea what happens here!

**Comment by SelenIT** [comment, marked as answer]
There is a small yet visible difference in the placement of semicircles with such value of `transform-origin`. `transform-origin:92.6q -39.7q` seems to work. It can be written shorter with percentages: `transform-origin:87.5%-75%` (i.e. the rotation center is placed at 7/8 horizontally and 3/4 vertically). This point has to be moved because elements are nested, so each element is shifted by the padding value from its parent.

You can compensate this shift by adding `translate` to the `transform` instead of changing `transform-origin`, e.g.
```css
<b><c><d><style>*{background:#191919;border-radius:53q 53q 0 0;position:fixed;margin:50}
*>*{padding:25 50;background:#F9E492}
b,d{background:#4F77FF}b,c,d{transform:translate(-25%,-200%)rotate(90deg
```
