### DISCUSSION TITLE
Solving #103, or how to beat Super Saiyan!

### DISCUSSION THREAD

**Discussion by Beowolve** [cssbattle/forum#249] [Show and tell]
I have noticed many players have problems with target #103, so I decided to share a pure CSS based version that gets 100% and works with the current backend as a reference for other players. Thx to Esger for providing a working base solution that I could optimize.
This target is definitely hard to get 100%. 

Here is the code:
```css
<a><a><a f><a u><a u k><a p><a p t><a f n><style>*{background:#161616;float:left}
[f]{--p:60 40;--x:88 36;--a:90deg;--n:#fdb 25%,#fff 0 50%}
[u]{--x:104 91 0-121;--a:150deg}
[k]{--a:30deg}
[p]{--x:58-238;--a:0 at 108q;--p:60}
[t]{--x:58-154;--a:180deg at 19q}
[n]{--x:178-146;--p:10;--n:#161616 50%}
a+a{--a:75deg}
a{padding:var(--p,30);margin:var(--x,122-135 0 133);border-radius:1in;background:conic-gradient(from var(--a,105deg),var(--n,#ebae11 50%),#0000 0
```

The code can be optimised even more. For example you can move the padding to `*`, but in that specific case u might get 99.9%. If that happens `#171717 `as background color solved it for me. This trick might also work for other solutions that struggle to get 100%.

Have fun ;)
