### DISCUSSION TITLE
Can anyone help me get 100% on Target #71 (“Elephant”)?

### DISCUSSION THREAD

**Discussion by brendandelany** [cssbattle/forum#346] [Q&A]
I’m trying to get a 100% match on [Battle #13, Target #71 “Elephant”](https://cssbattle.dev/play/71)—but I’m stuck at 99.5%.

Here is my code:

`<div a></div>
<div b></div>
<div c></div>
<style>
  body {
    background: #998235;
  }

  div, ::before, ::after {
    position: absolute;
    border-radius: 50%;
  }

  [a], [b] {
    height: 180px;
  }

  [a], [b]::after {
    background: #0B2429;
  }

  [a], [c] {
    width: 80px;
  }

  [a] {
    top: 60px;
    left: 50px;
    box-shadow: inset 16px 0 0 0 #1A4341;
    -webkit-box-reflect: right 140px;
  }

  ::before, ::after {
    content: "";
    width: 40px;
  }

  [b], [b]::after, [c] {
    margin: auto;
  }

  [b], [c] {
    inset: 0;
  }

  [b] {
    width: 180px;
    background: #1A4341;
  }

  [b]::before {
    top: 70px;
    left: 40px;
    height: 40px;
    background: radial-gradient(#0B2429 10px, #0000 10px), #998235;
    clip-path: inset(50% 0 0 0);
    -webkit-box-reflect: right 20px;
  }

  [b]::after {
    z-index: 1;
    top: 120px;
    left: 0;
    right: 0;
    height: 140px;
    border-radius: 20px;
  }

  [c] {
    top: 201px;
    height: 80px;
    border: 20px solid #FFF;
    clip-path: inset(0 0 50% 0);
  }
</style>`

My result and the example look exactly the same to me, but perhaps I’ve made an error somewhere. Can anyone help me figure out what’s going on?

(Also, I realize it’s possible a bug is causing my problems. If so, I’ll create a new post and tag it accordingly.)
<img width="1840" alt="Screen Shot 2023-06-03 at 4 18 22 PM" src="https://github.com/cssbattle/forum/assets/132954548/acf64c26-d07f-476a-b8b6-e4635c92ceb9">

**Comment by agrimsrud** [comment]
Even though it is rendered perfectly in your browser, it is not by CSS Battle. Preview your code using Beo's [CSS Battle Previewer](https://tc70f3.csb.app/) and you will see the right eye is missing.

As you can see, the box reflection is hidden by the clipping path. Does this get you any closer? :o)

`[b]::before {
  /* ... */
  clip-path: inset(50% 0 0 0);
  -webkit-box-reflect: right 20px;
}`

**Comment by Beowolve** [comment]
This works, I guess you are not using chrome. That is a common mistake, if you play CSSBattle always use Chrome/Chromium to avoid render differences.

```css
<p a><p b><p c><style> body { background: #998235 }
p, ::before, ::after {
position: absolute;
border-radius: 50%;
}

[a], [b] {
height: 180px;
}

[a], [b]::after {
background: #0B2429;
}

[a], [c] {
width: 80px;
}

[a] {
top:44;
left:50;
box-shadow: inset 16px 0 0 0 #1A4341;
-webkit-box-reflect: right 140px;
}

::before, ::after {
content: "";
width: 40px;
}

[b], [b]::after, [c] {
margin: auto;
}

[b], [c] {
inset: 0;
}

[b] {
width: 180px;
background: #1A4341;
}

[b]::before {
top: 70px;
left: 40px;
height: 40px;
background: radial-gradient(#0B2429 10px,#0000 0)#998235;
clip-path: inset(50%-200%0 0);
-webkit-box-reflect: right 20px;
}

[b]::after {
z-index: 1;
top: 120px;
left: 0;
right: 0;
height: 140px;
border-radius: 20px;
}
  
[c] {
top: 200px;
height: 80px;
border: 20px solid #FFF;
clip-path: inset(0 0 50% 0);
}
```
