### DISCUSSION TITLE
How to translate code from top solution to "normal code"?

### DISCUSSION THREAD

**Discussion by youth22341** [cssbattle/forum#377] [Q&A] [answered]
Hello guys, I'm a newbie to this channel - also with HTML,CSS field (I just joined CSSBattle about a week ago). Then, I feel so strange with tips and tricks here: ways to get code shorter and score higher. All targets I have solved, there are some targets that I cannot complete with 100% match (some of them are 99.9% match). Then I will find references from top solutions. But, when I read these codes, I do not understand that. Here is the code of Ilya Streltsyn's solution to daily target on 26/12/2023:
".<style>*{margin:282 36-146;box-shadow:16q -8cm 0-74q,-16q -8cm 0-74q,0-162q#fff,0-315q 0-42q#fff,0-230q 0-21q#fff,0 0 0 9cm,0-512q 0-4q#FF8D7A;color:642328}&{margin:77%120-167;border-radius:9in"
Because I'm new to HTML, CSS and joined this place to practice, I don't know about selector "&", what is "margin: 282 36-146" meaning...I have searched in the internet, chat GPT... but the result seems like it is invalid syntax. That makes me so confused.
I'm very happy if someone can help me to discover this, then I can enlarge my knowledge about this field. Thanks a lot ^^

**Comment by SelenIT** [comment, marked as answer]
Hello! Here is the unminified version of that code:
```html
<html>
  <head></head>
  <body><!-- all the tags before this point are optional -->
.<!-- a barely visible text content prevents rendering bug of empty body -->
<style>
```
```css
* { /* these styles apply to both html and body, unless overridden later */
  margin: 282px 36px -146px; /* top, both sides, bottom */
  box-shadow:
     16q -8cm 0 -74q,         /* on html: right eye, on body: invisible */
     -16q -8cm 0 -74q,        /* on html: left eye, on body: invisible */
     0 -162q #fff,            /* on html: bottom part of snowman body, on body: offscreen */
     0 -315q 0 -42q #fff,     /* on html: snowman head, on body: offscreen */
     0 -230q 0 -21q #fff,     /* on html: middle part of snowman body, on body: offscreen */
     0 0 0 9cm,               /* on html: fills the entire background, on body: covers the bottom part */
     0 -512q 0 -4q #FF8D7A;   /* on html: offscreen, on body: snowman's scarf */
   color: #642328             /* sets default color for shadows */
}
& { /* applies only to `html`  */
  margin: 77% 120px -167px;
  border-radius: 9in          /* makes the html element circular  */
} /* the browser assumes the code is complete even if this brace is omitted */
```
```html
</style><!-- the last open tag also is assumed complete even with no closing -->
  </body>
</html><!-- closing tags for body and html are optional too -->
```
Both start and end tags of the `html`, `head`, and `body` elements are [optional](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags), so the browser adds them to the DOM regardless their presence in the code and you can style them right off. Since there is no `doctype`, the browser interprets and renders the code in the so called "Quirks mode" (basically emulation of the the ancient browsers bugs to display correctly the pages that were designed relying on these bugs:). Usually it's considered a really bad practice, but for the code golfing purposes it [has some advantages](https://quirks.spec.whatwg.org/#css) like the ability to omit the `px` unit for some lengths and the `#` character for some colors (mostly for the basic properties from the CSS1 era). So those plain numbers in `margin` are actually just pixels.

The `&` selector belongs to the relatively newly released [CSS Nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting) syntax. When used not inside another rule, it's equivalent to `:root` but with zero specificity, so it applies to the `html` element only.

The dot char is needed only to make the `body` nonempty because otherwise its negative bottom margin results in wrong rendering (I assume it's a Chrome rendering bug, although it's hard to tell whether a bug is intentional in Quiks mode or not).

The whole shape is created with shadows of two elements — round `html` and rectangular `body`. The elements are placed so that the redundant parts are offscreen or/and squeezed to invisibility with negative spread radius, so the same shadow declaration can be reused for both, with no need to declare `box-shadow` twice.

CSSBattle also often makes use of some rarely used CSS units:
* `in` (inch) is defined equal to 96px. Useful for things "big enough", e.g., to cover the whole viewport.
* `cm` (centimeter) is about 37.8px. Adjusting the placement to make integer `cm`s work is a quite common micro-optimization tactic.
* `q` (quarter of a millimeter) is about 0.95px. It's the shortest CSS unit (only 1 character long) after plain-number pixels and percentages.
