### DISCUSSION TITLE
99% at #187

### DISCUSSION THREAD

**Discussion by ms-saltation** [cssbattle/forum#387] [General]
`<p><style>&{background:#40234B;>*{background:#A94EA4;margin:50 85;clip-path:polygon(0%0,50%100%,100%0)}p{height:10;background:#40234B;margin:0 -170 0 0;rotate:-60deg;box-shadow:0-26px,0-52px,0-78px,0-104px,0-130px,0-156px;color:40234B`

Cant do it to 100% :(

**Comment by SelenIT** [comment]
The thin line of the body background that "shines through" along the clipping path often prevents getting 100% match. It can be mitigated with setting `filter:blur(.1q)` for body, but it's usually better to invert the approach, i.e. use the shadows to create pink stripes themselves rather than dark intervals between them. The following quick change to your code gets 100% and also is a bit shorter:
```css
<p><style>&{background:#40234B;>*{margin:50 85;clip-path:polygon(0%0,50%100%,99.9%0)}p{height:16;margin:0-196 0 0;rotate:-60deg;box-shadow:0 2in inset,-4px 4px,0-26px,0-52px,0-78px,0-104px,0-130px,0-156px,0-182px;color:A94EA4
```
It can be optimized further by improving the margin and getting rid of the inset shadow.
