### ISSUE TITLE
Scoring 99.9% despite of perfect images overlapping

### ISSUE THREAD

**Issue by wblazej** [cssbattle/forum#345]
I get 99.9% score even tho the images are overlapping perfectly. Two examples below

## https://cssbattle.dev/play/145
<img width="883" alt="image" src="https://user-images.githubusercontent.com/62674438/235213443-0c347cd3-48d1-450e-b787-270c8b1c35cb.png">

### with Diff enabled
<img width="885" alt="image" src="https://user-images.githubusercontent.com/62674438/235213476-1cdcdb40-4d35-4507-92c3-5d5a3e0a9b4a.png">

### code
```css
<body bgColor=E3516E><a><b><style>a,b{position:fixed;background:#D9D9D9}a{padding:75;top:0;right:0}b{padding:75;border-radius:0 0 150px 150px;top:50;right:50;transform:rotate(45deg
```

## https://cssbattle.dev/play/144
<img width="882" alt="image" src="https://user-images.githubusercontent.com/62674438/235214068-e6b8db51-31d1-402e-9ebe-aa2322e47a8c.png">

### with Diff enabled
<img width="882" alt="image" src="https://user-images.githubusercontent.com/62674438/235213027-4c4a3fe7-0f41-40c3-af59-e1a3f380c5fd.png">

### code
```css
<body bgColor=62306D><c><d><a><b><style>a,b,c,d{background:#F7EC7D;position:fixed}a,b{padding:100 37.5;border-radius:50px 50px 0 0;left:0;top:100}c,d{padding:30;}c{left:75;top:165;}d{background:#62306D;left:75;top:165;border-radius:0 0 0 25px}b{left:62.5;top:162.5;transform:rotate(90deg
```

Screen: Retina 13,3" (2560x1600)

Maybe there are more of them 🤷‍♂️
